### ISSUE TITLE
BLEU upper limit 100？

### ISSUE THREAD

**Issue by nkjsy** [chiphuyen/machine-learning-systems-design#8]
@chiphuyen 
Hi Huyen I think the upper limit of BLEU score in machine translation is not 100. It is some float number between 4-6. I once did an experiment with all reference sentences to be the same as the hypothesis sentence and found the number. Just cannot remember it clearly.

**Comment by chiphuyen** [comment]
You might want to look up the definition of BLEU score: https://en.wikipedia.org/wiki/BLEU

**Comment by nkjsy** [comment]
Sorry it should be NIST score that in between 4-6. The BLUE upper limit is 100 you are right.
